# Generated by Django 5.0.2 on 2024-05-05 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naran', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Porfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulu', models.CharField(max_length=50)),
                ('deskrisaun', models.CharField(max_length=255)),
                ('imajen', models.ImageField(blank=True, null=True, upload_to='portfolio')),
                ('statos', models.BooleanField(default=False)),
                ('enderesu_url', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled')], default='draft', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(to='main.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naran', models.CharField(max_length=100)),
                ('data_hahu', models.DateField()),
                ('data_remata', models.DateField()),
                ('status', models.CharField(choices=[('Inisiu', 'Inisiu'), ('Prosesu hela', 'Prosesu hela'), ('Finalizadu', 'Finalizadu')], default='Inisiu', max_length=20)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categoria')),
                ('portfolio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='main.porfolio')),
            ],
        ),
    ]
