# Generated by Django 5.0.2 on 2024-03-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Porfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulu', models.CharField(max_length=50)),
                ('deskrisaun', models.CharField(max_length=255)),
                ('imajen', models.ImageField(blank=True, null=True, upload_to='portfolio')),
            ],
        ),
    ]
