# Generated by Django 5.0.2 on 2024-03-23 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_categoria_porfolio_enderesu_url_porfolio_statos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='portfolio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='main.porfolio'),
        ),
    ]
