# Generated by Django 5.0.2 on 2024-04-20 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='piblication_date',
            new_name='publication_date',
        ),
    ]
