"""
Django settings for blog project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ce1(--@t@1r$(989%4e*8%i#z51amp*s#9xcmh@fmrv!e8k&e*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True 
# se wainhira ita dev hela ita nia projetu maka Debug ida nee ita halo true no se launch ona iha publiku maka ita set ba falsa

ALLOWED_HOSTS = ['blog-73f3.onrender.com','127.0.0.1','localhost']

# ita nia local 


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'crispy_forms',
    'crispy_bootstrap4',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_summernote',
    'import_export',
    "main",
    # main ne'e foti bazeia ba app ne'ebe ita kria nia naran 
]

# install apps no library sira bele instala iha INSTALLED_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
# Konfigurasaun seguransa nian hanesan security authentication


ROOT_URLCONF = 'blog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# directory ba template ninian no ita bele bolu liu husi file nia naran no la presija nia directory kompletu

WSGI_APPLICATION = 'blog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# mysql connection
# DATABASES = {
#     'default' : {
#         'ENGINE' : 'django.db.backends.mysql',
#         'NAME' : 'db_blog',
#         'USER' : 'root',
#         'PASSWORD' : '',
#         'HOST' : '127.0.0.1',
#         'PORT' : '3306',
#         'OPTIONS' : {
#             'init_command' : 'SET sql_mode="STRICT_TRANS_TABLES"'
#         }
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

LOGIN_REDIRECT_URL = 'IndexAdmin'
LOGIN_URL = 'login'
CRISPY_TEMPLATE_PACK = 'bootstrap4'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

#aumenta link ba folder foto
MEDIA_ROOT = BASE_DIR/'media'
MEDIA_URL = '/media/'

# Ita mak rejistu ita nia folder 

STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
from django.contrib.messages import constants as message_constans
MESSAGE_TAGS ={
        message_constans.DEBUG: 'debug',
        message_constans.INFO: 'info',
        message_constans.SUCCESS: 'success',
        message_constans.WARNING: 'warning',
        message_constans.ERROR: 'danger',
    }
